sudo: required
dist: trusty
language: go
env:
  - GIMME_OS=linux GIMME_ARCH=amd64 PATH=$TRAVIS_BUILD_DIR/linux_amd64:$PATH
go:
  - 1.10
node_js:
  - 8
before_install:
  # Install the arm32 cross-compiler
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu artful main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gcc-arm-linux-gnueabi
  - arm-linux-gnueabi-gcc --version
  - sudo apt-get install -qq -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  # Install golang
  - gimme 1.10
  # Correct rake bug
  - RAKE=`which rake`
  - mv `which rake` `which rake`.old
  - touch ${RAKE}
  - chmod 755 ${RAKE}
install:
  # Module build
  - source /home/travis/.gimme/envs/go1.10.env
  - which go
  - go version
  # Build
  - cd $TRAVIS_BUILD_DIR/ui
  - make all
  # Module dependency
  - cd $TRAVIS_BUILD_DIR/core
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - dep ensure --update
  # Build
  - cd $TRAVIS_BUILD_DIR/core
  - make all
deploy:
  provider: releases
  overwrite: true
  api_key: "$GITHUB_OAUTH2_KEY"
  file:
  - "${GOPATH}/go-jarvis-0.0.1-SNAPSHOT.armel"
  - "${GOPATH}/go-jarvis-0.0.1-SNAPSHOT.armhf"
  - "${TRAVIS_BUILD_DIR}/scripts/go-jarvis-service"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy: curl -X POST http://${HOOK_SERVER}/travis/deployment/${TRAVIS_TAG}
